SELECT
	PCCLIENT.CODCLI,
	PCCLIENT.CLIENTE,
	REGEXP_REPLACE(PCCLIENT.CGCENT, '[^0-9]', '') AS CNPJ,
	PCCLIENT.ESTENT AS UF,
	UPPER(PCCIDADE.NOMECIDADE) AS CIDADE
FROM
	PCCLIENT
LEFT JOIN PCCIDADE ON
	PCCIDADE.CODCIDADE = PCCLIENT.CODCIDADE
WHERE PCCLIENT.TIPOFJ = 'J'
AND PCCLIENT.DTEXCLUSAO IS NULL
AND PCCLIENT.ESTENT IN ('PB','RN')
AND PCCLIENT.DTULTCOMP >= '01-jan-2021'